apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: dev

images:
  - name: arck8sregistry/.azurecr.io//azure-vote-front
    newTag: fb8e1d3f76c249de77bccad6a256d728fcd9ad98
  - name: arck8sregistry/.azurecr.io//azure-vote-back
    newTag: fb8e1d3f76c249de77bccad6a256d728fcd9ad98
resources:
  - manifests.yaml