apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: dev

images:
  - name: arck8sregistry/.azurecr.io//azure-vote-front
    newTag: 6655fe54af92519e442441ac5c229faa1517f9f2
  - name: arck8sregistry/.azurecr.io//azure-vote-back
    newTag: 6655fe54af92519e442441ac5c229faa1517f9f2
resources:
  - manifests.yaml